package org.e2ee.data.local.messages

import android.se.omapi.Session
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import org.e2ee.data.local.chatRoom.ChatRoom

@Entity(
    tableName = "messages",
    foreignKeys = [
        ForeignKey(
            entity = ChatRoom::class,
            parentColumns = ["sessionId"],
            childColumns = ["sessionId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class Messages(
    @PrimaryKey(autoGenerate = true)
    val localId : Long = 0L, // Auto-generated by Room

    val remoteMessageId: String,

    val sessionId: String,
    val content: String,
    val timestamp: Long,
    val status: MessageStatus,
    val isSentByUser: Boolean
)

enum class MessageStatus {
    SENT,
    DELIVERED,
    EXPIRED,
    FAILED,
    RECEIVED,
    SENDING
}
