package org.e2ee.data.local.messages

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable
import org.e2ee.data.local.chatRoom.ChatRoom

@Serializable
@Entity(
    tableName = "messages",
    foreignKeys = [
        ForeignKey(
            entity = ChatRoom::class,
            parentColumns = ["sessionId"],
            childColumns = ["sessionId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        androidx.room.Index(value = ["sessionId"])
    ]
)
data class Messages(
    @PrimaryKey(autoGenerate = true)
    val localId : Long = 0L, // Auto-generated by Room

    val remoteMessageId: String,

    val sessionId: String,
    val content: String,
    val timestamp: Long,
    val status: MessageStatus,
    val isSentByUser: Boolean
)

@Serializable
enum class MessageStatus {
    SENT,
    DELIVERED,
    EXPIRED,
    FAILED,
    RECEIVED,
    SENDING,

    READ_BY_RECEIVER
}
